### ISSUE TITLE
How frequent is too frequent?

### ISSUE THREAD

**Issue by wizonesolutions** [tmux-plugins/tmux-continuum#64]
It seems like if I `set -g @continuum-save-interval '1'`, that is too frequent, and my tmux sessions hang or crash (I am attached to multiple sessions in different physical terminal windows). I only have one server running. I saw the low interval from another tmux user, so I thought it was OK, but perhaps there is something weird about my usage triggering hangs while saving? It's usually just a hang, not a crash.

```
 ~/c/w/f/d/docroot   *  .ddev  cat ~/.tmux.conf                                                                      20.6s  17:16:42
#set -g default-terminal screen-256color
set -g history-limit 999999999

set -ga update-environment ' SSH_AUTH_SOCK'
#set-environment -g 'SSH_AUTH_SOCK' ~/.ssh/ssh_auth_sock
#set-environment -g 'SSH_AUTH_SOCK' /run/user/1000/keyring/ssh

#set-option -g default-command "reattach-to-user-namespace -l fish"

# # run bash first cuz fish is mean
# set-option -g default-shell /usr/bin/fish
# Just let bash set the environment, then drop to fish.
set-option -g default-command /usr/bin/fish

#bind '"' split-window -c "#{pane_current_path}"
#bind % split-window -h -c "#{pane_current_path}"
#bind c new-window -c "#{pane_current_path}"

set-option -g mouse on
set-option -g prefix C-a

bind -n M-PgDn select-window -n
bind -n M-PgUp select-window -p


# https://gist.github.com/spicycode/1229612
# Use Alt-arrow keys without prefix key to switch panes
#bind -n M-Left select-pane -L
#bind -n M-Right select-pane -R
#bind -n M-Up select-pane -U
#bind -n M-Down select-pane -D

# Use Alt-vim keys without prefix key to switch panes
bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R


set -g @resurrect-capture-pane-contents 'on'
set -g @resurrect-processes '~sshuttle'
set -g @continuum-boot 'on'
set -g @continuum-restore 'on'
set -g @continuum-save-interval '15'

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

# Other examples:
# set -g @plugin 'github_username/plugin_name'
# set -g @plugin 'git@github.com/user/plugin'
# set -g @plugin 'git@bitbucket.com/user/plugin'

set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-copycat'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-pain-control'


# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run -b '~/.tmux/plugins/tpm/tpm'
```

**Comment by dycw** [comment]
@royharoush, in #66, believes this ends up being interpreted as "every 1 second" as opposed to "every 1 minute". This could very much be the same hypothesis you're on.

If you search the current code (2021-02) for `continuum-save-interval` you'll find

https://github.com/tmux-plugins/tmux-continuum/blob/113826b161c1b1e54d2b5b3f26bd2fc8fc46ed92/scripts/variables.sh#L8

is then used in 

https://github.com/tmux-plugins/tmux-continuum/blob/9aac5ec93463638cfa5a87d0d71f8abd231bc161/scripts/continuum_save.sh#L13-L15

and a few lines down in 

https://github.com/tmux-plugins/tmux-continuum/blob/9aac5ec93463638cfa5a87d0d71f8abd231bc161/scripts/continuum_save.sh#L21-L27

Here there is clearly a conversion by 60. My guess is that everything does work as advertised.

The only reason I came here too is because I was looking to make the save a little more frequently, even considering 1 minute too. But when I saw this issue and @royharoush 's I got a little scared.

Any how, it's been 1.5 years since your issue @wizonesolutions . Have you seen any more problems?

**Comment by bruno-** [comment]
wizonesolutions has a huge window history limit `set -g history-limit 999999999` that is saved every minute due to `set -g @resurrect-capture-pane-contents 'on'`. Working with large window histories (saving / restoring) can take up time.

There are no hard rules for `@continuum-save-interval`. If you save/restore a single tmux window with small history - one minute would probably not cause problems.

Then again, why push it that hard? I think auto-save every hour is just fine, and that's what I'm using `set -g @continuum-save-interval '60'`

**Comment by bruno-** [comment]
Closing as this is not really a bug
